version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Workspace
permissions:
  - object: /home/ubuntu/Workspace
    owner: ubuntu
    group: ubuntu
hooks:
  BeforeInstall:
    - location: script/before_install.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: script/application_start.sh
      timeout: 300
      runas: ubuntu
